### ISSUE TITLE
This is an issue to annoy you

### ISSUE THREAD

**Issue by mrg0lden** [HebahAlshamlan/CertificateGenerator#1]
Hey, your project is good and all, but it doesn't have any issues, which is wrong. Humans do make mistakes; thus, there're issues to be resolved.

**Comment by mrg0lden** [comment]
@HebahAlshamlan Good aftermeme

**Comment by HebahAlshamlan** [comment]
Hi Dr. Mohammed 
I appreciate your admiration of the project,I think this issue has been solved now ;p
